#!/usr/bin/env bash
# This script displays "Bad luck", "Good luck", and "Best School"

i=0
while [ $i -lt 10 ]
    do
        if [ $i -eq 3 ]; then
            echo "Bad luck"
        elif [ $i -eq 7 ]; then
            echo "Good luck"
        else
            echo "Best School"
        fi
        i=$((i+1))
    done

