#!/usr/bin/env bash
# This script checks if a file exist

if [ -e "school" ] ; then
    echo "school file exists"
    if [ -s "school" ] ; then
        echo "school file is not empty"
    elif [ ! -s "school" ] ; then
        echo "school file is empty"
    elif [ -f "school" ] ; then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi