#!/bin/bash
export PATH=/home/bodemurairi/anaconda3/bin:/home/bodemurairi/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin/action
