#!/usr/bin/env bash
# This script terminates the script 4-to_infinity_and_beyond

# Get the PID of the script 4-to_infinity_and_beyond
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the process
if [ -n "$id" ]; 
then
    kill "$id"
    echo "Process $id terminated successfully"
fi