#!/usr/bin/env bash
# This script terminates the script 4-to_infinity_and_beyond

id=$(pgrep -f 4-to_infinity_and_beyond)
pgrep -f 4-to_infinity_and_beyond | xargs kill
echo "The script 4-to_infinity_and_beyond with id number $id has been terminated"