#!/usr/bin/env bash
# This script terminates the script 4-to_infinity_and_beyond without using kill or killall
# shellcheck disable=SC2009

pkill -f 4-to_infinity_and_beyond
echo "The script 4-to_infinity_and_beyond has been terminated"